services:
  app:
    build: .
    container_name: app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/src
    networks:
      - main
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    networks:
      - main
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - main
    ports:
      - 5601:5601
    restart: always

volumes:
  elasticsearch_volume:

networks:
  main:
